<?php
{{include file="header_template.tpl" shopEdition=$shopEdition}}

namespace {{$namespace}};

/**
 * Class {{$class.shortUnifiedClassName}}
 *
 * IMPORTANT:
 * This class has been generated by a script and is not meant to be edited.
 * Any changes will get lost during the next script run.
 *
{{if $class.isDeprecated}}
 * @deprecated See parent class for details.
 *
{{/if}}
 * @package {{$namespace}}
 */
{{include file="class_template.tpl" class=$class}}