<?php echo '<?php'; ?>

<?php include 'header_template.php'; ?>

namespace <?= $namespace ?>;

/**
 * Class <?= $class['shortUnifiedClassName'] ?>

 *
 * IMPORTANT:
 * This class has been generated by a script and is not meant to be edited.
 * Any changes will get lost during the next script run.
 *
<?php if ($class['isDeprecated']) : ?>
 * @deprecated See parent class for details.
 *
<?php endif; ?>
 * @package <?= $namespace ?>

 */
<?php include 'class_template.php'; ?>
