<?php

/**
 * Copyright © OXID eSales AG. All rights reserved.
 * See LICENSE file for license details.
 */

namespace OxidEsales\Eshop\Core\Contract;

/**
 * Class AbstractUpdatableFields
 *
 * IMPORTANT:
 * This class has been generated by a script and is not meant to be edited.
 * Any changes will get lost during the next script run.
 *
 * @package OxidEsales\Eshop\Core\Contract
 */
abstract class AbstractUpdatableFields extends \OxidEsales\EshopCommunity\Core\Contract\AbstractUpdatableFields
{
}
