<?php

/**
 * Copyright © OXID eSales AG. All rights reserved.
 * See LICENSE file for license details.
 */

namespace OxidEsales\Eshop\Application\Model;

/**
 * Class Article
 *
 * IMPORTANT:
 * This class has been generated by a script and is not meant to be edited.
 * Any changes will get lost during the next script run.
 *
 * @deprecated See parent class for details.
 *
 * @package OxidEsales\Eshop\Application\Model
 */
class Article extends \OxidEsales\EshopCommunity\Application\Model\Article
{
}

/**
 * This class alias is created for backwards compatibility only.
 * The class oxarticle is deprecated since OXID eShop v6.0.0 and should not be used any more as it
 * will be removed in the future.
 * Please use \OxidEsales\Eshop\Application\Model\Article instead.
 */
class_alias(\OxidEsales\Eshop\Application\Model\Article::class, 'oxarticle');
