<?php

/**
 * Copyright © OXID eSales AG. All rights reserved.
 * See LICENSE file for license details.
 */

namespace OxidEsales\Eshop\Core\Contract;

/**
 * Class IConfigurable
 *
 * IMPORTANT:
 * This class has been generated by a script and is not meant to be edited.
 * Any changes will get lost during the next script run.
 *
 * @package OxidEsales\Eshop\Core\Contract
 */
interface IConfigurable extends \OxidEsales\EshopCommunity\Core\Contract\IConfigurable
{

}

/**
 * This class alias is created for backwards compatibility only.
 * The class oxiconfigurable is deprecated since OXID eShop v6.0.0 and should not be used any more as it
 * will be removed in the future.
 * Please use \OxidEsales\Eshop\Core\Contract\IConfigurable instead.
 */
class_alias(\OxidEsales\Eshop\Core\Contract\IConfigurable::class, 'oxiconfigurable');
